### ISSUE TITLE
Ajax Complete + Error Status Code not working

### ISSUE THREAD

**Issue by chobo2** [aFarkas/Ajaxmanager#3] opened 2010-07-03 00:43 UTC
Hi

See this post. http://stackoverflow.com/questions/3169419/jquery-ajax-complete-not-getting-custom-reponse-header

You also really need to add some examples on how use these new call backs like the global ones I have no clue how to get them to work and I been trying for like 2 hours.

**Comment by aFarkas** [comment] 2010-07-04 08:27
Hi,

I have commited a fix for this issue. I haven't testet it yet, but due to the fact that this was only a small change, it should work now. Wich global new event do you want to use?

regards
alex

**Comment by chobo2** [comment] 2010-07-04 18:19
So what did you fix exactly out of my post? I wanted to use global complete. But I think have to use "error" since ajaxmanager throws an error when using 403 status code and in IE 8 the user gets a javascript console warning.

**Comment by aFarkas** [comment] 2010-07-04 19:35
Hi,

I have fixed the issue where your callback  is overwritten, if you use the $.ajaxSetup-method. Note that this is fixed in the version control only (version 3.05RC).

jQuery's ajax method also would call the error-callback, if your server returns 403 code.

you can do something like this using ajaxSetup now, there was a bug:

```
$.ajaxSetup
({
    complete: function (xhr, status, options)
    {
        if (xhr.getResponseHeader('X-LOGON') === 'LogOn')
        {

            window.location.href = "redirect to signin";
        }
    }
});
```

If you want to use the global event, you can use something like this (This is normal to jQuery's and I don't explain these features):

```
$(document).bind('ajaxComplete', function(e, xhr, options){
    if (xhr.getResponseHeader('X-LOGON') === 'LogOn')
    {
        window.location.href = "redirect to signin";
    }
});
```

This is documented here: http://api.jquery.com/ajaxComplete/

If you want, you can also stick to the error handler due to the fact, that this is a redirect for an error. I hope this helps. Please contact me again, if I misunderstood your needs or there is still a bug in the script.

**Comment by chobo2** [comment] 2010-07-05 20:18
Thanks for the fast replies. I thought .ajaxSetup was a global setup. I will check out the newest version and get back to you thanks.

**Comment by aFarkas** [comment] 2010-09-18 22:35
cannot reproduce

**Closed as completed by aFarkas** 2010-09-18 22:35 UTC
